[package]
name = "awair-monitor"
version = "0.1.0"
authors = ["Olly Legg <olly@51degrees.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
